---
- name: 01 - Test Collection Precedence and Installation
  hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Ensure collections from requirements.yml are installed
      # This task executes the ansible-galaxy command using the credentials defined on the Organization.
      ansible.builtin.shell: |
        ansible-galaxy collection install -r collections/requirements.yml --force
      args:
        # The playbook_dir variable ensures Ansible finds the collections/requirements.yml file in the project directory.
        chdir: "{{ playbook_dir }}"
      # The output of the shell command (stdout/stderr) will show where the collections were downloaded from.
      register: collection_install_result
      
    - name: Display installation results (Optional check the log for specific URLs)
      ansible.builtin.debug:
        msg: "Installation Output: {{ collection_install_result.stdout_lines }}"

    - name: Verify dalibo.advanced was installed (proof of PAH priority)
      # This task is a placeholder to show successful execution after installation.
      # The success of the previous shell command is the true verification.
      ansible.builtin.meta: noop
      # register: pah_success # Removed unnecessary register here

    - name: Output status
      ansible.builtin.debug:
        msg: "Collection installation check complete. Check the job log for the source URL used."